spring.application.name=spring_ymldemo

#my-key.key1 = bite
#key1: java
#key2: java

---
string:
str1: Hello \n Spring Boot.
str2: 'Hello \n Spring Boot.'
str3: "Hello \n Spring Boot"

#????
---
student:
id: 1
name: java
age: 18

#????
---
dbtypes:
name:
- mysql
- sqlserver
- db2
